KPI_MANAGER_VERSION = '/v1'
KPI_MANAGER_HOST = 'https://kpi.annotell.com'
GOOGLE_CLOUD_DATAPROC = 'GOOGLE_CLOUD_DATAPROC'
GOOGLE_KPI_BUCKET = 'gs://annotell-kpi-manager/'
LOCALHOST = 'localhost'
AMAZON_SPARK_EMR = 'AMAZON_SPARK_EMR'
AMAZON_KPI_BUCKET = 's3://magna-elec-adas-kpi-dev/'
