import requests
import datetime
import json

from annotell.kpi.logging import get_logger
from annotell.auth.authsession import AuthSession

log = get_logger()


class FileManager:
    def __init__(self, auth_session: AuthSession, host, project_id: int, job_id: str, kpi_manager_version):
        self.auth_session = auth_session
        self.host = host
        self.project_id = project_id
        self.job_id = job_id
        self.kpi_manager_version = kpi_manager_version

    def create_file(self, filename: str, description: str):
        """Create a file object to find a file generated by the script
        """
        file_info = {
            "filename": filename,
            "description": description,
            "project_id": self.project_id,
            "job_id": self.job_id,
            "created": str(datetime.datetime.now())
        }
        headers = {'Content-Type': 'application/json'}
        try:
            return self.auth_session.post(
                url=self.host + self.kpi_manager_version + "/file/create",
                data=json.dumps(file_info),
                headers=headers
            )
        except requests.exceptions.ConnectionError:
            log.error(f"Cannot submit event, the server={self.host} probably did not respond")
            return None
